site_name: Max & George Universe
nav:
    - Home: 
        - icon: material/home
        - index.md
    - Language: 
        - icon: material/translate
        - Overview: language/index.md
        - Grammar: language/grammar.md
    - Biology:
        - icon: material/dna
        - Overview: biology/index.md
        - Xorakion: biology/xorakion.md
    - Characters & Places:
        - icon: material/map-marker
        - Overview: world/index.md

theme:
  name: material
  palette:
    primary: '#1a1a2e'    # Deep blue from avatar
    accent: '#ffd700'     # Golden color from avatar
    scheme: slate
  icon:
    repo: material/github
