site_name: Max & George Universe
nav:
    - Home: index.md
    - Language: 
        - Overview: language/index.md
        - Grammar: language/grammar.md
    - Biology:
        - Overview: biology/index.md
        - Xorakion: biology/xorakion.md
    - Characters & Places:
        - Overview: world/index.md

theme:
  name: material
  palette:
    # Dark theme
    primary: '#1a1a2e'    # Deep blue from avatar
    accent: '#ffd700'     # Golden color from avatar
    scheme: slate         # Dark theme base
