site_name: Max & George Universe
nav:
    - Home: index.md
    - Language: 
        - Overview: language/index.md
        - Grammar: language/grammar.md
    - Biology:
        - Overview: biology/index.md
        - Xorakion: biology/xorakion.md
    - Characters & Places:
        - Overview: world/index.md

theme: readthedocs
